import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'

const inter = Nunito({ subsets: ['latin'] })

import ReactQueryProvider from '../providers/ReactQueryProvider';

import { Navbar } from '@/components/Navbar';

import { getCurrentUser } from '@/actions/getCurrentUser';

import { RegisterModal } from '@/components/modals/RegisterModal';
import { LoginModal } from '@/components/modals/LoginModal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar
            currentUser={currentUser}
          />
          <div className="flex flex-row flex-wrap w-full m-auto max-w-[1168px] p-8">
            {children}
          </div>
          <RegisterModal />
          <LoginModal />
        </body>
      </html>
    </ReactQueryProvider>
  )
}
