import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import ReactQueryProvider from '../providers/ReactQueryProvider';

import { Navbar } from '@/components/Navbar';

import { RegisterModal } from '@/components/modals/RegisterModal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <div className="flex flex-row flex-wrap w-full m-auto max-w-[1168px] p-8">
            {children}
          </div>
          <RegisterModal />
        </body>
      </html>
    </ReactQueryProvider>
  )
}
